[package]
name = "memgraph"
version = "0.1.0"
edition = "2024"

[dependencies]
inferno = "0.12.0"
anyhow = "1.0"
clap = "4.5"
open = "5.3"
reqwest = { version = "0.12", features = ["blocking"] }

[dependencies.memtrack]
git = "https://github.com/blkmlk/memtrack-rs"